name: kiwiibot_dart
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.3 <3.0.0'

dev_dependencies:
  build_runner: ^2.1.11
  lints: ^2.0.0
  test: ^1.16.0

dependencies: 
  analyzer: ^3.4.1
  args: ^2.3.1
  nyxx: ^3.4.2
  nyxx_commands: ^4.2.0
  path: ^1.8.2
  slang: ^2.6.1
  postgres: ^2.4.5
  image: ^3.2.0
  http: ^0.13.4
  build: ^2.3.0
  source_gen: ^1.2.2
